[[CvxCompress]]
arch = "aarch64"
git-tree-sha1 = "b5d0896d24c4f8adbeeaf57ac4c87b1d4ea5ae94"
os = "macos"

    [[CvxCompress.download]]
    sha256 = "991478b3141dbcd84bfd9452cd25c34491b3a3013db39a9195c343d58037126e"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.aarch64-apple-darwin.tar.gz"
[[CvxCompress]]
arch = "aarch64"
git-tree-sha1 = "c9f6704f78c84a749c0a65f71df543e7b0696946"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "c6c5877dd67d9ab6a60e3063897f372289d17fe3d7b7f7d4861182792efe17d2"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.aarch64-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "aarch64"
git-tree-sha1 = "60ac229c13dc1d56e22a49978dbb6cdd792e8e5e"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "dcab39d68b4231b54770b7def83a67aee5004f152a13e30b534a8e767e79d9d8"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.aarch64-linux-musl.tar.gz"
[[CvxCompress]]
arch = "aarch64"
git-tree-sha1 = "cdf77be402f71466d2b6af4870fb3c2392067d8e"
os = "freebsd"

    [[CvxCompress.download]]
    sha256 = "9d83565ac118f1144c272dcd2487cca9bb06459826f7d6408c5ec0fe20305301"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.aarch64-unknown-freebsd.tar.gz"
[[CvxCompress]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "656302331df66aefe1e2b1c494022a55f466ac9f"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "677c638359a8bd6958ae2749560d8d21a5170abcb53ab84391b53535f045199b"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.armv6l-linux-gnueabihf.tar.gz"
[[CvxCompress]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d2342770cea15a04e7f489ca3a1b86533fa79d6a"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "639878a257d04dd79b963a70954a9c7b7f89fa98297771da3514354bcc4d6edf"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.armv6l-linux-musleabihf.tar.gz"
[[CvxCompress]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "356478fa2d2f526384881d99d2784ab092f6dfeb"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "35970fef096d6f3e149bdd106bbb51b89409719c3a1c3ef6686e3455a5a90223"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.armv7l-linux-gnueabihf.tar.gz"
[[CvxCompress]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "885e57924c98d4925e04a1a1e71104ecd8d66b4f"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "fc8413abb89c5999e629e3096afa031c38ddbc31096ead134ea59ce18dbaa45d"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.armv7l-linux-musleabihf.tar.gz"
[[CvxCompress]]
arch = "i686"
git-tree-sha1 = "fe648379988cb1ebceb73c6b83ef27cdde57a614"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "063463e4a6fe90171f0cffa19ce324eb874462a4c154323e088e6ffa8622aaf1"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.i686-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "i686"
git-tree-sha1 = "a36225bcbff6d1b0f986b8100041aee0a5753315"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "4f4fc7916318e28c500d0c312d77e518deac0b7eeb6e52355740bffc73a5b18c"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.i686-linux-musl.tar.gz"
[[CvxCompress]]
arch = "powerpc64le"
git-tree-sha1 = "c9e2e2ff8182cc5ab096dc55391258a3cb4595c9"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "4681883a4717ffb68e727d7b49a3d8ec8f7dec2e889d29efd55f38f2f6d13b56"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.powerpc64le-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "a133de701b1ec5247ce19dbabf018e6ce3a1e237"
os = "macos"

    [[CvxCompress.download]]
    sha256 = "4aa4af5ad214e625aa5d7ef76ca5b3bf783be0d5892a80d783e5f396fe8c6626"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.x86_64-apple-darwin.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "378a06e0ce34532742b956fbdae5065c0676187b"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "72effc28d219ea1770b30ae55d600e4f3cbfd0ab7bb74bd54e6ed88fecff7f07"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.x86_64-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "410880275fe791d1639ed165f24c879ba6b1853a"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "c8c2ed95fc74fc68eccc04794721e7c62acc96ecd1e988d585bc12af08e9f8ef"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.x86_64-linux-musl.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "4b932458e24cc22d0bf4a5682fda3b4fe8fc6477"
os = "freebsd"

    [[CvxCompress.download]]
    sha256 = "7d9573e36c891cce8f69c43781023b873b386faed9b3f1571abec544aa75528f"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.2.1+0/CvxCompress.v1.2.1.x86_64-unknown-freebsd.tar.gz"
