[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "e70528e5af19b211500972e6f92a34184a93a629"
os = "macos"

    [[CvxCompress.download]]
    sha256 = "7e8194df9b0ec096f4678e8c27e13edc3dd62e9f5fc4416c61ed57f01a75b33f"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.0.0+0/CvxCompress.v1.0.0.x86_64-apple-darwin14.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "9428d26a72d3e82e16bd937e5389fa8960915f5f"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "f29819d56db4b6bde1564597b6fbfcf0de7895171728e8e045623e62a501e3f6"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.0.0+0/CvxCompress.v1.0.0.x86_64-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "04dad7f8c071f5e281928ccb6a2d636969cf424c"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "9420c943a1cd510db2fb5870ae6bfc20a5df95e0cd3d23322439c32490edf65c"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.0.0+0/CvxCompress.v1.0.0.x86_64-linux-musl.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "542678256225be53831be5dbc676892dcd4eb9be"
os = "freebsd"

    [[CvxCompress.download]]
    sha256 = "0bb3057e21b79bc86ec44e4f8be177fa8f7438d65ad59335f75dd40a99e36ede"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.0.0+0/CvxCompress.v1.0.0.x86_64-unknown-freebsd11.1.tar.gz"
