[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "21b5bffd29e520029e57b7038608c0118cc94472"
os = "macos"

    [[CvxCompress.download]]
    sha256 = "12812c1b9b42eb993cd86cea9ee6bb4c4622b3645513437eb49085a515c1a6fb"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.1.0+0/CvxCompress.v1.1.0.x86_64-apple-darwin.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "9d219bef036bf6a922ee91ae6b93675868fc90f0"
libc = "glibc"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "ab742f69e44276d403a503d36f2bda3d564e98b6a7bbe399e96c2a44328551e9"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.1.0+0/CvxCompress.v1.1.0.x86_64-linux-gnu.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "7a77e5b7728ee0d19c7943f69f810ee18ebec18b"
libc = "musl"
os = "linux"

    [[CvxCompress.download]]
    sha256 = "78f1424443a9422e47066c623c6b358510527b541be6ad8bf37cdd4280b1fbca"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.1.0+0/CvxCompress.v1.1.0.x86_64-linux-musl.tar.gz"
[[CvxCompress]]
arch = "x86_64"
git-tree-sha1 = "7dd10eabce91c453dde5b3fc66e794e647defd02"
os = "freebsd"

    [[CvxCompress.download]]
    sha256 = "010bc73221aa7bc975bff525b48fefd3ef9bfe0e1f15abff248bcf11f89c94b5"
    url = "https://github.com/JuliaBinaryWrappers/CvxCompress_jll.jl/releases/download/CvxCompress-v1.1.0+0/CvxCompress.v1.1.0.x86_64-unknown-freebsd.tar.gz"
